"""Update ProviderPatient or UserRecommendation models

Revision ID: 323ae91a726e
Revises: b59e828af45c
Create Date: 2024-12-13 10:47:57.231687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323ae91a726e'
down_revision = 'b59e828af45c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_patients', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('user_recommendations', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))

    with op.batch_alter_table('provider_patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###
