"""adjustschema

Revision ID: 40858df077d4
Revises: 240edf69c4f6
Create Date: 2024-12-30 10:17:13.300234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40858df077d4'
down_revision = '240edf69c4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'])

    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'])

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))

    with op.batch_alter_table('provider_patients', schema=None) as batch_op:
        batch_op.drop_constraint('provider_patients_patient_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('provider_patients_patient_id_fkey', 'users', ['patient_id'], ['id'])

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
